ptz:
  name: ptz
  description: Pan/Tilt service for yi-hack camera.
  fields:
    entity_id:
      name: Entity id
      description: Name of entity to move.
      required: true
      example: "camera.living_room_camera"
      selector:
        entity:
          integration: yi_hack
          domain: camera
    movement:
      name: Direction of the movement
      description: "Direction of the movement. Allowed values: up, down, left and right."
      required: true
      example: "left"
      selector:
        select:
          options:
            - "up"
            - "down"
            - "left"
            - "right"
    travel_time:
      name: Travel time
      description: "(Optional) Travel time in seconds. Allowed values: float from 0.1 to 5.0. Default: 0.3"
      required: false
      example: 0.3
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
          unit_of_measurement: "s"
          mode: box

move_to_preset:
  name: Move to a preset
  description: Aim camera at the defined preset
  fields:
    entity_id:
      name: Entity id
      description: Name of entity to move.
      required: true
      example: "camera.living_room_camera"
      selector:
        entity:
          integration: yi_hack
          domain: camera
    preset_id:
      name: Preset id
      description: "Id of the preset to go to"
      required: true
      example: 0
      selector:
        number:
          min: 0
          max: 14
          mode: box

speak:
  name: speak
  description: TTS service for yi-hack camera.
  fields:
    entity_id:
      name: Entity id
      description: Name of entity to use.
      required: true
      example: "camera.living_room_camera"
      selector:
        entity:
          integration: yi_hack
          domain: camera
    language:
      name: Language
      description: "Language of the TTS engine"
      required: true
      example: "en-US"
      selector:
        select:
          options:
            - "ar-EG"
            - "ar-SA"
            - "bg-BG"
            - "ca-ES"
            - "cs-CZ"
            - "da-DK"
            - "de-AT"
            - "de-CH"
            - "de-DE"
            - "el-GR"
            - "en-AU"
            - "en-CA"
            - "en-GB"
            - "en-IE"
            - "en-IN"
            - "en-US"
            - "es-ES"
            - "es-MX"
            - "fi-FI"
            - "fr-CA"
            - "fr-CH"
            - "fr-FR"
            - "he-IL"
            - "hi-IN"
            - "hr-HR"
            - "hu-HU"
            - "id-ID"
            - "it-IT"
            - "ja-JP"
            - "ko-KR"
            - "ms-MY"
            - "nb-NO"
            - "nl-NL"
            - "pl-PL"
            - "pt-BR"
            - "pt-PT"
            - "ro-RO"
            - "ru-RU"
            - "sk-SK"
            - "sl-SI"
            - "sv-SE"
            - "ta-IN"
            - "te-IN"
            - "th-TH"
            - "tr-TR"
            - "vi-VN"
            - "zh-CN"
            - "zh-HK"
            - "zh-TW"
    gender:
      description: "Gender of the TTS engine"
      required: true
      example: "en-US"
      selector:
        select:
          options:
            - "male"
            - "female"
    sentence:
      name: Sentence to pronounce
      description: "Sentence to pronounce"
      required: true
      example: "Hello world!"
      selector:
        text:

reboot:
  name: Reboot the cam
  description: Reboot the camera
  fields:
    entity_id:
      name: Entity id
      description: Name of entity to reboot.
      required: true
      example: "camera.living_room_camera"
      selector:
        entity:
          integration: yi_hack
          domain: camera
